[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "beautifulsoup4>=4.12.3",
    "trafilatura>=2.0.0",
    "lxml>=5.0.0",
    "cssselect>=1.2.0",
]
